language: python
python:
  - "3.6"

notifications:
  email: false

service:
  - postgresql

env:
  - DATABASE_NAME='imagersite' SECRET_KEY='potato' DATABASE_HOST='127.0.0.1' DATABASE_USER='postgres'

before_script:
  - psql -c "create database imagersite;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python imagersite/manage.py migrate
  - imagerstie/manage.py test