language: python
python:
  - "3.6"

notifications:
  email: false

service:
  - postgresql

before_script:
  - psql -c "create database imagersite;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - python imagersite/manage.py migrate
  - imagerstie/manage.py test