- hosts: us-west-2a
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Update the Ubuntu system and services
      apt: update_cache=yes

    - name: Install Basic Unix-level Services
      apt: name={{ item }} state=latest
      with_items:
        - nginx
        - python3
        - python3-pip
        - python3.4-venv
        - git
        - gunicorn

    - name: Clone the Imager App to the Home Directory
      git: 
        clone=yes
        repo=https://github.com/adriennekarnoski/django-imager.git
        dest=/home/ubuntu/imagersite
        version=deployment

    - name: Create a virtual environment in the imager app repo
      command: python3 -m venv /home/ubuntu/imagersite/ENV

    - name: Install gunicorn to the virtualenv
      pip: virtualenv=/home/ubuntu/imagersite name=gunicorn

    - name: Create a new default file for nginx
      template: src=../templates/nginx_config.jinja2 dest=/etc/nginx/sites-available/default

    - name: Restart nginx service
      service: name=nginx state=restarted

    - name: Copy upstart script into /etc/init
      template: src=../templates/upstart_config dest=/etc/init/imagersite.conf
      
    - name: Restart the imagersite upstart job
      service: name=imagersite state=restarted
